# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\x12\x08tutorial\"\xab\x01\n\x0eRequestForWork\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x10\n\x08typeName\x18\x02 \x01(\t\x12\x16\n\x0eWorkloadMetric\x18\x03 \x01(\x05\x12\x11\n\tBatchUnit\x18\x04 \x01(\x05\x12\x0f\n\x07\x42\x61tchID\x18\x05 \x01(\x05\x12\x11\n\tBatchSize\x18\x06 \x01(\x05\x12\x11\n\tdata_type\x18\x07 \x01(\t\x12\x15\n\rDataAnalytics\x18\x08 \x01(\t\"i\n\x0fResponseForData\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x14\n\x0c\x46inalBatchID\x18\x02 \x01(\x05\x12\x19\n\rProcessedData\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x15\n\rDataAnalytics\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSEFORDATA.fields_by_name['ProcessedData']._options = None
  _RESPONSEFORDATA.fields_by_name['ProcessedData']._serialized_options = b'\020\001'
  _REQUESTFORWORK._serialized_start=29
  _REQUESTFORWORK._serialized_end=200
  _RESPONSEFORDATA._serialized_start=202
  _RESPONSEFORDATA._serialized_end=307
# @@protoc_insertion_point(module_scope)
